// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Cycle is an autogenerated mock type for the Cycle type
type Cycle struct {
	mock.Mock
}

// Run provides a mock function with given fields:
func (_m *Cycle) Run() {
	_m.Called()
}
